server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mabdelhamid/cloud-config.git
          force-pull: true
          ignoreLocalSshSettings: true
          repos:
            common:
              uri: https://github.com/mabdelhamid/cloud-config.git
              force-pull: true
              searchPaths: common/*
              order: 1
            beneficiary:
              uri: https://github.com/mabdelhamid/cloud-config.git
              force-pull: true
              searchPaths: dpy/beneficiary
              order: 2
            payment:
              uri: https://github.com/mabdelhamid/cloud-config.git
              force-pull: true
              searchPaths: dpy/payment
              order: 2

management.security.enabled: false
logging.level.org.springframework.web: DEBUG